<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="pradhanssingh" ignored="0" name="sample test" tests="2" failures="2" timestamp="2020-05-21T19:12:42 IST" time="9.247" errors="0">
  <testcase name="login" time="0.009" classname="com.nt.test.FacebookLoginClass">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.nt.test.FacebookLoginClass.login(FacebookLoginClass.java:22)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- login -->
  <testcase name="login" time="9.223" classname="com.nt.test.FacebookLoginClass">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.nt.listener.TestNGListener.onTestFailure(TestNGListener.java:34)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- sample test -->
